### ISSUE TITLE
Swiss and French Quotes

### ISSUE THREAD

**Issue by jwssnr** [ohanhi/atom-highlight-bad-chars#14]
Hi. I really love your plugin. It is very helpful for copy-pasting text to Atom. Also for my Students who are beginners in coding. There’s only a little thing, which is unnecessarily disturbing my eyes: « and » are quotes in Swiss and French and they aren’t bad chars in UTF8 documents. 
Cheers, Jürgen

**Comment by WaKeMaTTa** [comment]
I propose a solution, but i don't know how to do it.

**Solution**

Add an option to "Ignore bad chars in comments".

Example:

```html
<!-- « im a coment » -->
```

**Comment by ohanhi** [comment]
I suppose at least the double arrow quotes (« and ») are easily distinguished from the less/greater thans, since they only occupy one character slot. The single arrow quotes (‹ and ›) are much more likely to be confused. So I reckon, maybe the doubles' highlight could be removed altogether?

**Comment by jwssnr** [comment]
My opinion: Only sort of empty spaces (invisible chars) can be bad chars. The single quotes me be used very rarly but they are also part of Swiss and French for quotes within quotes. The problem of visualy separating similar characters should be job of the font-face.

**Comment by olehermanse** [comment]
@jwssnr Some characters are _supposed to_ look very similar. (See greek question mark). I think several people use this package to find confusing commas, quotes, and other punctuation which would cause syntax errors in their programming language. It's not just for invisible characters.

This package targets programmers who write source code, not arbitrary UTF-8 documents. ( I like that these quotes are highlighted, even though we use the same quotes in Norwegian, my native language ).

I think the proper solution here would be to add settings to the package, allowing users to enable/disable different categories of "bad characters". Categories could be "Invisible characters", "Weird Whitespace", "Confusing punctuation" etc.

**Comment by ohanhi** [comment]
I have now added a first iteration of the categories as toggleable settings. Does this solve your issue?

**Comment by olehermanse** [comment]
@ohanhi Can I suggest a category for highlight everything except printable ascii? This would cover the need for a lot of people who just write code in English (People who use this option would not have to manually update the highlight list like we have in the past).

**Comment by ohanhi** [comment]
Hmm, why not. You reckon disallowing `controlCharacters`, No break space, and anything above `\u0080` would do the trick?

**Comment by olehermanse** [comment]
Anything outside of 32-126 (decimal) can be highlighted. Below 32 is control, 127 is DEL, 128+ is unicode.

**Comment by olehermanse** [comment]
> Anything outside of 32-126 (decimal) can be highlighted. Below 32 is control, 127 is DEL, 128+ is unicode.

@ohanhi I think this option, along with the ability to add a custom list of whitelisted characters would solve a lot of the issues / discussions about what should and shouldn't be highlighted in this package.

**Comment by jwssnr** [comment]
> @ohanhi I think this option, along with the ability to add a custom list of whitelisted characters would solve a lot of the issues / discussions about what should and shouldn't be highlighted in this package.

I totally agree. Everything else would be a never ending story.

**Comment by ohanhi** [comment]
@olehermanse Okay, now that I've thought this through and am no longer sentimental about my precious character lists (sunken costs and so on), I do agree with you. 

There is no real value in blacklisting specific characters in the source code context, where only a tiny subset of characters is actually valid. And the user-defined whitelist will allow everyone to have their favorite quotes and language-specific letters without highlights. Furthermore, this simplifies the code a lot and probably makes the regex match faster. I will do this tomorrow.
