### ISSUE TITLE
Hangs the editor

### ISSUE THREAD

**Issue by stugol** [ohanhi/atom-highlight-bad-chars#2]
If I do a regex search for `[\0]`, then use `find-and-replace:find-all` to create cursors for each match, the editor deadlocks. This does not happen when your plugin is not active.

Obviously my file contains a lot of hidden nulls.

**Comment by ohanhi** [comment]
I would imagine this was fixed in Atom 1.23, as the `onDidChange` event was fired _per cursor_ before that version, and now it only fires once per change. If this is still an issue, I'll reopen.
