### ISSUE TITLE
Microsoft Word special unicode characters

### ISSUE THREAD

**Issue by ctrlbrk42** [ohanhi/atom-highlight-bad-chars#21]
Can we please update the special Microsoft Word unicode characters for apostrophe's and quotation marks?

![image](https://user-images.githubusercontent.com/1001097/49888777-d8323880-fe0d-11e8-8d53-919c364806b5.png)

Example:
- What�s the scope with exchange hosted servers<br/>

**Comment by ohanhi** [comment]
I do not have access to Microsoft Word. What are all the characters (preferably in hexadecimal + explanation format) that you would like to see highlighted?
