### ISSUE TITLE
All lines are now red

### ISSUE THREAD

**Issue by dennisaskeland** [ohanhi/atom-highlight-bad-chars#24]
Hello,

the last update leaves all lines in all my files red. It highlights everything as an error. See attached screenshot @ohanhi 

<img width="1244" alt="screenshot 2019-01-07 at 11 20 07" src="https://user-images.githubusercontent.com/9537270/50762760-37009b80-126e-11e9-9578-c246dd831d3f.png">

**Comment by ohanhi** [comment]
Hmm... Can you give me an example snippet and some basic information (your OS and Atom version)?

**Comment by ohanhi** [comment]
Oh I see the problem, I accidentally added CR and LF to the highlighted characters. I'll push a fix soon!

**Comment by ohanhi** [comment]
@dennisaskeland I've published 1.4.1. Can you confirm this works for you?

**Comment by olehermanse** [comment]
@ohanhi from the screenshot, it looks like tabs are also highlighted.

**Comment by dennisaskeland** [comment]
I've updated to 1.4.1, and restarted Atom but the issue seems to persist unfortunately

**Comment by ohanhi** [comment]
@dennisaskeland I think you may need to toggle one of the settings checkboxes to purge the old data, and then reload Atom.

**Comment by dennisaskeland** [comment]
You're right. Unchecked, reloaded and then checked again. Seems to be working as expected now. Thanks for quick feedback, and great package—life saver!

**Comment by ohanhi** [comment]
Sweet. For posterity, the affected safe characters were:
- tab `\x09`
- line feed (LF) `\x0A`
- carriage return (CR) `\x0D`
