### ISSUE TITLE
Highlight bad character sequences

### ISSUE THREAD

**Issue by riyad** [ohanhi/atom-highlight-bad-chars#4]
There're invalid/incomplete character UTF-8 sequences that editors handle "gracefully" but cause errors when running a script.
Maybe you could also highlight those byte sequences also.

**Comment by riyad** [comment]
Maybe [this (PHP) regexp](https://stackoverflow.com/questions/11709410/regex-to-detect-invalid-utf-8-string) can be adapted.
Or you might have a look at [Markus Kuhn’s UTF-8 decoder stress test](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt).

**Comment by ohanhi** [comment]
I suspect this may cause quite a performance hit, but now that I've introduced settings, I guess this could be added an opt-in feature (off by default). Do you think that would make sense?

**Comment by riyad** [comment]
This would be a useful feature even if it was behind a flag. :slightly_smiling_face:

**Comment by ohanhi** [comment]
Well now that I switched to using a whitelist, I think this may be solved. Can you verify?

**Comment by riyad** [comment]
yes, it highlights all weird cases from [Markus Kuhn’s UTF-8 decoder stress test](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt).

Sadly now I have a similar but unrelated problem. :cry: Atom seems to render valid, but "undisplayable" characters (i.e. unprintable, control, missing font) same as invalid sequences: i.e. with �. :sob:

weird, but valid sequences:
![valid sequences](https://user-images.githubusercontent.com/99679/50904107-bd101400-141f-11e9-87ba-bb5fbd863d81.png)

invalid sequences:
![invalid sequences](https://user-images.githubusercontent.com/99679/50904120-c5684f00-141f-11e9-8aee-fa5f61b3e957.png)

But I'll try to figure this out separately.

Thank you. :slightly_smiling_face:
